service: app

provider:
    name: aws
    region: us-east-2
    environment:
        APP_CLIENT_ID: ${ssm:/vta-apsys/client-id}
        USER_POOL_ID: ${ssm:/vta-apsys/user-pool-id}
        IDENTITY_POOL_ID: ${ssm:/vta-apsys/identity-pool-id}
        REGION: us-east-2
        ES_ENDPOINT: ${ssm:/vta-apsys/es-endpoint}
        ES_USER: ${ssm:/vta-apsys/es-user}
        ES_PASS: ${ssm:/vta-apsys/es-pass}

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: index.php
        description: 'The backend api of the vta application system'
        runtime: php-84-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            -   httpApi: '*'
    
    postConfirmation:
        handler: functions/postConfirmation.php
        description: Handle cognito post confirmation
        runtime: php-84
        package:
            exclude:
                - 'node_modules/**'
                - 'tests/**'
                - 'http/**'
                - 'routes/**'
                - 'controllers/**'
                - 'bootstrap/**'

    referenceStream:
        handler: functions/referenceStream.php
        description: Handle reference table stream
        runtime: php-84
        events:
        - stream:
            type: dynamodb
            arn: arn:aws:dynamodb:us-east-2:182399695457:table/vta_appsys_referencedata/stream/2025-04-13T08:22:44.154
            batchSize: 1
            startingPosition: TRIM_HORIZON
        package:
            exclude:
                - 'node_modules/**'
                - 'tests/**'
                - 'http/**'
                - 'routes/**'
                - 'controllers/**'
                - 'bootstrap/**'

    applicationStream:
        handler: functions/applicationStream.php
        description: Handle applications table stream
        runtime: php-84
        events:
        - stream:
            type: dynamodb
            arn: arn:aws:dynamodb:us-east-2:182399695457:table/vta_appsys_applications/stream/2025-04-13T08:23:16.396
            batchSize: 1
            startingPosition: TRIM_HORIZON
        package:
            exclude:
                - 'node_modules/**'
                - 'tests/**'
                - 'http/**'
                - 'routes/**'
                - 'controllers/**'
                - 'bootstrap/**'

# Exclude files from deployment
package:
    patterns:
        - '!node_modules/**'
        - '!tests/**'
        - '!public'
        - '!views'
